baseurl = "/"
languageCode = "en-gb"
title = "Healthforge"

[permalinks]
  incidents = "/incidents/:year/:month/:day/:slug/"

[params]
  defaultLogo = "https://www.netlify.com/img/press/logos/logomark.svg"
  faviconsPath = "/images/favicon/"

systems = ["API", "Auth", "Foo", "Bar"]
